ALTER TABLE users ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE article ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE comment ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE wishlist ADD COLUMN version BIGINT NOT NULL DEFAULT 0;